/**
 * ThemeMate telemetry receiver for Google Apps Script.
 * Generated by scripts/generate_telemetry_artifacts.py from telemetry/schema.json.
 */

const TELEMETRY_SCHEMA = {
  "schema_version": 1,
  "max_len": 128,
  "accepted_keys": [
    "session_id",
    "role",
    "mode",
    "platform",
    "outcome",
    "failure_category",
    "escalated_to",
    "store_domain",
    "lines_written",
    "turns",
    "session_duration_min",
    "exit_summary",
    "satisfaction",
    "feedback_reason",
    "feedback_note",
    "git_org",
    "git_repo",
    "pr_url",
    "preview_url",
    "email_domain"
  ],
  "enums": {
    "role": [
      "swym_acq",
      "swym_success",
      "swym_support",
      "swym_staff",
      "agency",
      "merchant",
      "unknown"
    ],
    "mode": [
      "KNOWLEDGE",
      "THEME_INSPECT",
      "THEME_EDIT"
    ],
    "platform": [
      "shopify",
      "bigcommerce",
      "headless",
      "unknown"
    ],
    "outcome": [
      "completed",
      "blocked",
      "error",
      "scope_rejected"
    ],
    "failure_category": [
      "app_embed_hidden",
      "css_specificity_conflict",
      "snippet_removed_on_update",
      "json_template_priority",
      "callback_race_condition",
      "zindex_stacking",
      "hot_reload_stale",
      "non_theme_liquid_layout",
      "theme_access_denied",
      "shopify_cli_auth_failure",
      "push_failed",
      "out_of_scope",
      "browser_automation_failure",
      "other"
    ],
    "escalated_to": [
      "swym_engineering",
      "shopify_support",
      "bigcommerce_support",
      "none"
    ],
    "satisfaction": [
      "positive",
      "neutral",
      "negative"
    ],
    "feedback_reason": [
      "incorrect_output",
      "didnt_solve_issue",
      "too_slow",
      "unclear_explanation",
      "other"
    ]
  },
  "column_order": [
    "received_at",
    "event",
    "ts",
    "install_id",
    "skill",
    "skill_version",
    "schema_version",
    "session_id",
    "role",
    "mode",
    "platform",
    "outcome",
    "failure_category",
    "escalated_to",
    "store_domain",
    "lines_written",
    "turns",
    "session_duration_min",
    "exit_summary",
    "satisfaction",
    "feedback_reason",
    "feedback_note",
    "git_org",
    "git_repo",
    "pr_url",
    "preview_url",
    "email_domain"
  ]
};
const TELEMETRY_COLUMNS = ["received_at", "event", "ts", "install_id", "skill", "skill_version", "schema_version", "session_id", "role", "mode", "platform", "outcome", "failure_category", "escalated_to", "store_domain", "lines_written", "turns", "session_duration_min", "exit_summary", "satisfaction", "feedback_reason", "feedback_note", "git_org", "git_repo", "pr_url", "preview_url", "email_domain"];
const SHEET_NAME = 'events';
const TOKEN_PROPERTY_KEY = 'THEMEMATE_TOKEN';

// The daily `heartbeat` event (skill-updater.sh) is a fixed, session-less
// install ping -- a reach/adoption signal, not a ThemeMate session. It never
// carries session_id or any of the richer session fields, so it gets its own
// sheet with a fixed minimal shape instead of cluttering `events` with
// mostly-blank rows and instead of evolving alongside schema.json's
// session-oriented accepted_keys/column_order.
const HEARTBEAT_SHEET_NAME = 'heartbeat';
const HEARTBEAT_COLUMNS = ['received_at', 'ts', 'install_id', 'skill', 'skill_version'];

function doPost(e) {
  try {
    const raw = parseBody_(e);
    if (!raw || typeof raw !== 'object') {
      return jsonResponse_(400, { ok: false, error: 'invalid_json' });
    }

    if (!isAuthorized_(raw)) {
      return jsonResponse_(403, { ok: false, error: 'unauthorized' });
    }

    const normalized = normalizePayload_(raw);

    if (normalized.event === 'heartbeat') {
      const sheet = getOrCreateSheet_(HEARTBEAT_SHEET_NAME);
      const headers = ensureHeaders_(sheet, HEARTBEAT_COLUMNS);
      appendRow_(sheet, headers, normalized);
      return jsonResponse_(200, { ok: true });
    }

    const sheet = getOrCreateSheet_(SHEET_NAME);
    const headers = ensureHeaders_(sheet, TELEMETRY_COLUMNS);
    upsertRow_(sheet, headers, normalized);

    return jsonResponse_(200, { ok: true });
  } catch (err) {
    return jsonResponse_(500, { ok: false, error: String(err) });
  }
}

function parseBody_(e) {
  if (!e || !e.postData || !e.postData.contents) return null;
  return JSON.parse(e.postData.contents);
}

function isAuthorized_(payload) {
  const configured = PropertiesService.getScriptProperties().getProperty(TOKEN_PROPERTY_KEY);
  if (!configured) return true;
  return String(payload.token || '') === String(configured);
}

function normalizePayload_(payload) {
  const maxLen = Number(TELEMETRY_SCHEMA.max_len || 128);
  const accepted = new Set(TELEMETRY_SCHEMA.accepted_keys || []);
  const enums = TELEMETRY_SCHEMA.enums || {};

  const out = {
    received_at: new Date().toISOString(),
    event: truncate_(payload.event, maxLen),
    ts: truncate_(payload.ts, maxLen),
    install_id: truncate_(payload.install_id, maxLen),
    skill: truncate_(payload.skill, maxLen),
    skill_version: truncate_(payload.skill_version, maxLen),
    // Not read from the caller's payload -- a caller could otherwise write an
    // arbitrary schema_version into the sheet. This receiver only ever
    // understands its own embedded TELEMETRY_SCHEMA, so that's the only
    // truthful value to record.
    schema_version: TELEMETRY_SCHEMA.schema_version
  };

  for (const key of accepted) {
    if (!(key in payload)) continue;
    const value = truncate_(payload[key], maxLen);
    if (Object.prototype.hasOwnProperty.call(enums, key)) {
      if (!enums[key].includes(value)) continue;
    }
    out[key] = value;
  }

  return out;
}

function getOrCreateSheet_(sheetName) {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  let sheet = ss.getSheetByName(sheetName);
  if (!sheet) sheet = ss.insertSheet(sheetName);
  return sheet;
}

function ensureHeaders_(sheet, desiredHeaders) {
  const headerRow = 1;
  const lastCol = Math.max(1, sheet.getLastColumn());
  // Keep blanks in place -- every other function indexes into this array by
  // physical column position (headers.indexOf(...), headers.map((h, i) =>
  // ...)). Filtering them out here would desync those indices from the
  // sheet's actual columns the moment row 1 has any gap.
  const existingHeaders = sheet.getRange(headerRow, 1, 1, lastCol).getValues()[0];
  const hasAnyHeader = existingHeaders.some((v) => String(v || '').trim() !== '');

  if (!hasAnyHeader) {
    sheet.getRange(headerRow, 1, 1, desiredHeaders.length).setValues([desiredHeaders]);
    return desiredHeaders.slice();
  }

  const existingSet = new Set(existingHeaders.map((v) => String(v || '')));
  const missing = desiredHeaders.filter((h) => !existingSet.has(h));
  if (missing.length === 0) return existingHeaders;

  const startCol = lastCol + 1;
  sheet.getRange(headerRow, startCol, 1, missing.length).setValues([missing]);
  return existingHeaders.concat(missing);
}

function upsertRow_(sheet, headers, payload) {
  const sessionCol = headers.indexOf('session_id');
  const existingRow = (sessionCol === -1 || !payload.session_id)
    ? -1
    : findRowBySessionId_(sheet, sessionCol, payload.session_id);

  if (existingRow === -1) {
    appendRow_(sheet, headers, payload);
    return;
  }

  // Merge onto the existing row: only overwrite columns present on this event's
  // payload (e.g. a session_heartbeat's turns/session_duration_min), leave every
  // other column -- role, store_domain, git_org, etc. set by an earlier event in
  // the same session -- untouched rather than blanked out.
  const lastCol = headers.length;
  const currentValues = sheet.getRange(existingRow, 1, 1, lastCol).getValues()[0];
  const merged = headers.map((h, i) => (
    Object.prototype.hasOwnProperty.call(payload, h) ? payload[h] : currentValues[i]
  ));
  sheet.getRange(existingRow, 1, 1, lastCol).setValues([merged]);
}

function findRowBySessionId_(sheet, sessionCol, sessionId) {
  const lastRow = sheet.getLastRow();
  if (lastRow < 2) return -1;
  const values = sheet.getRange(2, sessionCol + 1, lastRow - 1, 1).getValues();
  for (let i = values.length - 1; i >= 0; i--) {
    if (values[i][0] === sessionId) return i + 2;
  }
  return -1;
}

function appendRow_(sheet, headers, payload) {
  const row = headers.map((h) => (Object.prototype.hasOwnProperty.call(payload, h) ? payload[h] : ''));
  sheet.appendRow(row);
}

function truncate_(value, maxLen) {
  if (value === undefined || value === null) return '';
  return String(value).slice(0, maxLen);
}

function jsonResponse_(status, obj) {
  // Apps Script web app responses are always HTTP 200 regardless of this
  // value (ContentService has no way to set the real status code) -- fold
  // it into the body so callers can still tell success from failure.
  const body = Object.assign({ status: status }, obj);
  const output = ContentService.createTextOutput(JSON.stringify(body));
  output.setMimeType(ContentService.MimeType.JSON);
  return output;
}
