/**
 * ThemeMate telemetry receiver for Google Apps Script.
 * Generated by scripts/generate_telemetry_artifacts.py from telemetry/schema.json.
 */

const TELEMETRY_SCHEMA = {
  "schema_version": 1,
  "max_len": 128,
  "accepted_keys": [
    "session_id",
    "role",
    "mode",
    "platform",
    "outcome",
    "failure_category",
    "escalated_to",
    "store_domain",
    "lines_written",
    "satisfaction",
    "feedback_reason",
    "feedback_note",
    "git_org",
    "git_repo",
    "pr_url",
    "preview_url",
    "email_domain"
  ],
  "enums": {
    "role": [
      "swym_acq",
      "swym_success",
      "swym_support",
      "swym_staff",
      "agency",
      "merchant",
      "unknown"
    ],
    "mode": [
      "KNOWLEDGE",
      "THEME_INSPECT",
      "THEME_EDIT"
    ],
    "platform": [
      "shopify",
      "bigcommerce",
      "headless",
      "unknown"
    ],
    "outcome": [
      "completed",
      "blocked",
      "error",
      "scope_rejected"
    ],
    "failure_category": [
      "app_embed_hidden",
      "css_specificity_conflict",
      "snippet_removed_on_update",
      "json_template_priority",
      "callback_race_condition",
      "zindex_stacking",
      "hot_reload_stale",
      "non_theme_liquid_layout",
      "theme_access_denied",
      "shopify_cli_auth_failure",
      "push_failed",
      "out_of_scope",
      "browser_automation_failure",
      "other"
    ],
    "escalated_to": [
      "swym_engineering",
      "shopify_support",
      "bigcommerce_support",
      "none"
    ],
    "satisfaction": [
      "positive",
      "neutral",
      "negative"
    ],
    "feedback_reason": [
      "incorrect_output",
      "didnt_solve_issue",
      "too_slow",
      "unclear_explanation",
      "other"
    ]
  },
  "column_order": [
    "received_at",
    "event",
    "ts",
    "install_id",
    "skill",
    "skill_version",
    "schema_version",
    "session_id",
    "role",
    "mode",
    "platform",
    "outcome",
    "failure_category",
    "escalated_to",
    "store_domain",
    "lines_written",
    "satisfaction",
    "feedback_reason",
    "feedback_note",
    "git_org",
    "git_repo",
    "pr_url",
    "preview_url",
    "email_domain"
  ]
};
const TELEMETRY_COLUMNS = ["received_at", "event", "ts", "install_id", "skill", "skill_version", "schema_version", "session_id", "role", "mode", "platform", "outcome", "failure_category", "escalated_to", "store_domain", "lines_written", "satisfaction", "feedback_reason", "feedback_note", "git_org", "git_repo", "pr_url", "preview_url", "email_domain"];
const SHEET_NAME = 'events';
const TOKEN_PROPERTY_KEY = 'THEMEMATE_TOKEN';

function doPost(e) {
  try {
    const raw = parseBody_(e);
    if (!raw || typeof raw !== 'object') {
      return jsonResponse_(400, { ok: false, error: 'invalid_json' });
    }

    if (!isAuthorized_(raw)) {
      return jsonResponse_(403, { ok: false, error: 'unauthorized' });
    }

    const normalized = normalizePayload_(raw);
    const sheet = getOrCreateSheet_();
    ensureHeaders_(sheet, TELEMETRY_COLUMNS);
    appendRow_(sheet, TELEMETRY_COLUMNS, normalized);

    return jsonResponse_(200, { ok: true });
  } catch (err) {
    return jsonResponse_(500, { ok: false, error: String(err) });
  }
}

function parseBody_(e) {
  if (!e || !e.postData || !e.postData.contents) return null;
  return JSON.parse(e.postData.contents);
}

function isAuthorized_(payload) {
  const configured = PropertiesService.getScriptProperties().getProperty(TOKEN_PROPERTY_KEY);
  if (!configured) return true;
  return String(payload.token || '') === String(configured);
}

function normalizePayload_(payload) {
  const maxLen = Number(TELEMETRY_SCHEMA.max_len || 128);
  const accepted = new Set(TELEMETRY_SCHEMA.accepted_keys || []);
  const enums = TELEMETRY_SCHEMA.enums || {};

  const out = {
    received_at: new Date().toISOString(),
    event: truncate_(payload.event, maxLen),
    ts: truncate_(payload.ts, maxLen),
    install_id: truncate_(payload.install_id, maxLen),
    skill: truncate_(payload.skill, maxLen),
    skill_version: truncate_(payload.skill_version, maxLen),
    schema_version: truncate_(payload.schema_version, maxLen)
  };

  for (const key of accepted) {
    if (!(key in payload)) continue;
    const value = truncate_(payload[key], maxLen);
    if (Object.prototype.hasOwnProperty.call(enums, key)) {
      if (!enums[key].includes(value)) continue;
    }
    out[key] = value;
  }

  return out;
}

function getOrCreateSheet_() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  let sheet = ss.getSheetByName(SHEET_NAME);
  if (!sheet) sheet = ss.insertSheet(SHEET_NAME);
  return sheet;
}

function ensureHeaders_(sheet, desiredHeaders) {
  const headerRow = 1;
  const lastCol = Math.max(1, sheet.getLastColumn());
  const existingValues = sheet.getRange(headerRow, 1, 1, lastCol).getValues()[0];
  const existingHeaders = existingValues.filter((v) => String(v || '').trim() !== '');

  if (existingHeaders.length === 0) {
    sheet.getRange(headerRow, 1, 1, desiredHeaders.length).setValues([desiredHeaders]);
    return;
  }

  const existingSet = new Set(existingHeaders);
  const missing = desiredHeaders.filter((h) => !existingSet.has(h));
  if (missing.length === 0) return;

  const startCol = existingHeaders.length + 1;
  sheet.getRange(headerRow, startCol, 1, missing.length).setValues([missing]);
}

function appendRow_(sheet, headers, payload) {
  const row = headers.map((h) => (Object.prototype.hasOwnProperty.call(payload, h) ? payload[h] : ''));
  sheet.appendRow(row);
}

function truncate_(value, maxLen) {
  if (value === undefined || value === null) return '';
  return String(value).slice(0, maxLen);
}

function jsonResponse_(status, obj) {
  const output = ContentService.createTextOutput(JSON.stringify(obj));
  output.setMimeType(ContentService.MimeType.JSON);
  return output;
}
