#!/usr/bin/env python3
"""Generate telemetry artifacts from telemetry/schema.json.

Artifacts:
- telemetry-emit.sh generated schema block
- telemetry/apps-script/Code.gs

Usage:
  python3 scripts/generate_telemetry_artifacts.py
  python3 scripts/generate_telemetry_artifacts.py --check
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "telemetry" / "schema.json"
EMITTER_PATH = ROOT / "telemetry-emit.sh"
APPS_SCRIPT_PATH = ROOT / "telemetry" / "apps-script" / "Code.gs"

EMITTER_START = "# BEGIN GENERATED TELEMETRY SCHEMA - DO NOT EDIT MANUALLY"
EMITTER_END = "# END GENERATED TELEMETRY SCHEMA"


def compact_json(value: object) -> str:
    return json.dumps(value, ensure_ascii=True, separators=(", ", ": "))


def load_schema() -> dict:
    try:
        data = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise SystemExit(f"Missing schema file: {SCHEMA_PATH}")

    required = ["schema_version", "max_len", "accepted_keys", "enums", "column_order"]
    missing = [k for k in required if k not in data]
    if missing:
        raise SystemExit(f"Schema missing keys: {', '.join(missing)}")

    accepted = data["accepted_keys"]
    enums = data["enums"]
    column_order = data["column_order"]

    if len(set(accepted)) != len(accepted):
        raise SystemExit("accepted_keys contains duplicates")
    if any(not isinstance(k, str) or not k for k in accepted):
        raise SystemExit("accepted_keys must be non-empty strings")

    if any(not isinstance(k, str) or not k for k in column_order):
        raise SystemExit("column_order must be non-empty strings")
    if len(set(column_order)) != len(column_order):
        raise SystemExit("column_order contains duplicates")

    for enum_key in enums:
        if enum_key not in accepted:
            raise SystemExit(f"enum key '{enum_key}' not listed in accepted_keys")
        values = enums[enum_key]
        if not values or len(set(values)) != len(values):
            raise SystemExit(f"enum '{enum_key}' must have unique values")

    expected_base = [
        "received_at",
        "event",
        "ts",
        "install_id",
        "skill",
        "skill_version",
        "schema_version",
    ]
    for key in expected_base:
        if key not in column_order:
            raise SystemExit(f"column_order missing base column '{key}'")

    for key in accepted:
        if key not in column_order:
            raise SystemExit(f"column_order missing accepted key '{key}'")

    return data


def render_emitter_block(schema: dict) -> str:
    keys_json = compact_json(schema["accepted_keys"])
    enums_json = compact_json(schema["enums"])
    return "\n".join(
        [
            EMITTER_START,
            f"SCHEMA_KEYS_JSON='{keys_json}'",
            f"SCHEMA_ENUMS_JSON='{enums_json}'",
            f"SCHEMA_MAX_LEN='{int(schema['max_len'])}'",
            EMITTER_END,
        ]
    )


def update_emitter(schema: dict) -> str:
    text = EMITTER_PATH.read_text(encoding="utf-8")
    pattern = re.compile(
        re.escape(EMITTER_START) + r"[\s\S]*?" + re.escape(EMITTER_END),
        re.MULTILINE,
    )
    replacement = render_emitter_block(schema)
    if not pattern.search(text):
        raise SystemExit("Could not find generated schema block markers in telemetry-emit.sh")
    return pattern.sub(replacement, text, count=1)


def render_apps_script(schema: dict) -> str:
    schema_json = json.dumps(schema, ensure_ascii=True, indent=2)
    columns = json.dumps(schema["column_order"], ensure_ascii=True)
    return f"""/**
 * ThemeMate telemetry receiver for Google Apps Script.
 * Generated by scripts/generate_telemetry_artifacts.py from telemetry/schema.json.
 */

const TELEMETRY_SCHEMA = {schema_json};
const TELEMETRY_COLUMNS = {columns};
const SHEET_NAME = 'events';
const TOKEN_PROPERTY_KEY = 'THEMEMATE_TOKEN';

// The daily `heartbeat` event (skill-updater.sh) is a fixed, session-less
// install ping -- a reach/adoption signal, not a ThemeMate session. It never
// carries session_id or any of the richer session fields, so it gets its own
// sheet with a fixed minimal shape instead of cluttering `events` with
// mostly-blank rows and instead of evolving alongside schema.json's
// session-oriented accepted_keys/column_order.
const HEARTBEAT_SHEET_NAME = 'heartbeat';
const HEARTBEAT_COLUMNS = ['received_at', 'ts', 'install_id', 'skill', 'skill_version'];

function doPost(e) {{
  try {{
    const raw = parseBody_(e);
    if (!raw || typeof raw !== 'object') {{
      return jsonResponse_(400, {{ ok: false, error: 'invalid_json' }});
    }}

    if (!isAuthorized_(raw)) {{
      return jsonResponse_(403, {{ ok: false, error: 'unauthorized' }});
    }}

    const normalized = normalizePayload_(raw);

    if (normalized.event === 'heartbeat') {{
      const sheet = getOrCreateSheet_(HEARTBEAT_SHEET_NAME);
      const headers = ensureHeaders_(sheet, HEARTBEAT_COLUMNS);
      appendRow_(sheet, headers, normalized);
      return jsonResponse_(200, {{ ok: true }});
    }}

    const sheet = getOrCreateSheet_(SHEET_NAME);
    const headers = ensureHeaders_(sheet, TELEMETRY_COLUMNS);
    upsertRow_(sheet, headers, normalized);

    return jsonResponse_(200, {{ ok: true }});
  }} catch (err) {{
    return jsonResponse_(500, {{ ok: false, error: String(err) }});
  }}
}}

function parseBody_(e) {{
  if (!e || !e.postData || !e.postData.contents) return null;
  return JSON.parse(e.postData.contents);
}}

function isAuthorized_(payload) {{
  const configured = PropertiesService.getScriptProperties().getProperty(TOKEN_PROPERTY_KEY);
  if (!configured) return true;
  return String(payload.token || '') === String(configured);
}}

function normalizePayload_(payload) {{
  const maxLen = Number(TELEMETRY_SCHEMA.max_len || 128);
  const accepted = new Set(TELEMETRY_SCHEMA.accepted_keys || []);
  const enums = TELEMETRY_SCHEMA.enums || {{}};

  const out = {{
    received_at: new Date().toISOString(),
    event: truncate_(payload.event, maxLen),
    ts: truncate_(payload.ts, maxLen),
    install_id: truncate_(payload.install_id, maxLen),
    skill: truncate_(payload.skill, maxLen),
    skill_version: truncate_(payload.skill_version, maxLen),
    // Not read from the caller's payload -- a caller could otherwise write an
    // arbitrary schema_version into the sheet. This receiver only ever
    // understands its own embedded TELEMETRY_SCHEMA, so that's the only
    // truthful value to record.
    schema_version: TELEMETRY_SCHEMA.schema_version
  }};

  for (const key of accepted) {{
    if (!(key in payload)) continue;
    const value = truncate_(payload[key], maxLen);
    if (Object.prototype.hasOwnProperty.call(enums, key)) {{
      if (!enums[key].includes(value)) continue;
    }}
    out[key] = value;
  }}

  return out;
}}

function getOrCreateSheet_(sheetName) {{
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  let sheet = ss.getSheetByName(sheetName);
  if (!sheet) sheet = ss.insertSheet(sheetName);
  return sheet;
}}

function ensureHeaders_(sheet, desiredHeaders) {{
  const headerRow = 1;
  const lastCol = Math.max(1, sheet.getLastColumn());
  // Keep blanks in place -- every other function indexes into this array by
  // physical column position (headers.indexOf(...), headers.map((h, i) =>
  // ...)). Filtering them out here would desync those indices from the
  // sheet's actual columns the moment row 1 has any gap.
  const existingHeaders = sheet.getRange(headerRow, 1, 1, lastCol).getValues()[0];
  const hasAnyHeader = existingHeaders.some((v) => String(v || '').trim() !== '');

  if (!hasAnyHeader) {{
    sheet.getRange(headerRow, 1, 1, desiredHeaders.length).setValues([desiredHeaders]);
    return desiredHeaders.slice();
  }}

  const existingSet = new Set(existingHeaders.map((v) => String(v || '')));
  const missing = desiredHeaders.filter((h) => !existingSet.has(h));
  if (missing.length === 0) return existingHeaders;

  const startCol = lastCol + 1;
  sheet.getRange(headerRow, startCol, 1, missing.length).setValues([missing]);
  return existingHeaders.concat(missing);
}}

function upsertRow_(sheet, headers, payload) {{
  const sessionCol = headers.indexOf('session_id');
  const existingRow = (sessionCol === -1 || !payload.session_id)
    ? -1
    : findRowBySessionId_(sheet, sessionCol, payload.session_id);

  if (existingRow === -1) {{
    appendRow_(sheet, headers, payload);
    return;
  }}

  // Merge onto the existing row: only overwrite columns present on this event's
  // payload (e.g. a session_heartbeat's turns/session_duration_min), leave every
  // other column -- role, store_domain, git_org, etc. set by an earlier event in
  // the same session -- untouched rather than blanked out.
  const lastCol = headers.length;
  const currentValues = sheet.getRange(existingRow, 1, 1, lastCol).getValues()[0];
  const merged = headers.map((h, i) => (
    Object.prototype.hasOwnProperty.call(payload, h) ? payload[h] : currentValues[i]
  ));
  sheet.getRange(existingRow, 1, 1, lastCol).setValues([merged]);
}}

function findRowBySessionId_(sheet, sessionCol, sessionId) {{
  const lastRow = sheet.getLastRow();
  if (lastRow < 2) return -1;
  const values = sheet.getRange(2, sessionCol + 1, lastRow - 1, 1).getValues();
  for (let i = values.length - 1; i >= 0; i--) {{
    if (values[i][0] === sessionId) return i + 2;
  }}
  return -1;
}}

function appendRow_(sheet, headers, payload) {{
  const row = headers.map((h) => (Object.prototype.hasOwnProperty.call(payload, h) ? payload[h] : ''));
  sheet.appendRow(row);
}}

function truncate_(value, maxLen) {{
  if (value === undefined || value === null) return '';
  return String(value).slice(0, maxLen);
}}

function jsonResponse_(status, obj) {{
  // Apps Script web app responses are always HTTP 200 regardless of this
  // value (ContentService has no way to set the real status code) -- fold
  // it into the body so callers can still tell success from failure.
  const body = Object.assign({{ status: status }}, obj);
  const output = ContentService.createTextOutput(JSON.stringify(body));
  output.setMimeType(ContentService.MimeType.JSON);
  return output;
}}
"""


def write_if_changed(path: Path, new_text: str, check_only: bool) -> bool:
    old_text = path.read_text(encoding="utf-8") if path.exists() else ""
    if old_text == new_text:
        return False
    if check_only:
        return True
    path.write_text(new_text, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if generated files are out of date")
    args = parser.parse_args()

    schema = load_schema()
    updated = []

    emitter_text = update_emitter(schema)
    if write_if_changed(EMITTER_PATH, emitter_text, args.check):
        updated.append(str(EMITTER_PATH.relative_to(ROOT)))

    apps_script_text = render_apps_script(schema)
    if write_if_changed(APPS_SCRIPT_PATH, apps_script_text, args.check):
        updated.append(str(APPS_SCRIPT_PATH.relative_to(ROOT)))

    if args.check and updated:
        print("Generated telemetry artifacts are out of date:")
        for path in updated:
            print(f"- {path}")
        print("Run: python3 scripts/generate_telemetry_artifacts.py")
        return 1

    if updated:
        print("Updated telemetry artifacts:")
        for path in updated:
            print(f"- {path}")
    else:
        print("Telemetry artifacts are already up to date.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
